// Yahoo Finance ticker symbols for theme holdings
// Only publicly traded companies with reliable tickers are included
// Suffix guide: .L (London), .T (Tokyo), .DE (Germany), .PA (Paris),
// .MC (Madrid), .MI (Milan), .ST (Stockholm), .CO (Copenhagen),
// .HK (Hong Kong), .NS (NSE India), .AX (Australia), .SA (Brazil),
// .MX (Mexico), .KS (Korea), .SI (Singapore), .JK (Jakarta),
// .BK (Bangkok), .SR (Saudi)

export const TICKER_MAP = {
  // European Defense
  'Rheinmetall': 'RHM.DE',
  'BAE Systems': 'BA.L',
  'Leonardo': 'LDO.MI',
  'Thales': 'HO.PA',
  'Saab': 'SAAB-B.ST',
  'Dassault Aviation': 'AM.PA',
  'Hensoldt': 'HAG.DE',
  'Kongsberg Gruppen': 'KOG.OL',
  'Rolls-Royce': 'RR.L',
  'Chemring': 'CHG.L',
  'QinetiQ': 'QQ.L',
  'Indra Sistemas': 'IDR.MC',
  'Babcock International': 'BAB.L',
  'Elbit Systems': 'ESLT',

  // Japan Financials
  'Mitsubishi UFJ': '8306.T',
  'Sumitomo Mitsui': '8316.T',
  'Mizuho': '8411.T',
  'Nomura': '8604.T',
  'Daiwa': '8601.T',
  'Tokio Marine': '8766.T',
  'Japan Post Bank': '7182.T',
  'Resona Holdings': '8308.T',
  'SBI Holdings': '8473.T',
  'Concordia Financial': '7186.T',
  'Dai-ichi Life': '8750.T',
  'T&D Holdings': '8795.T',
  'MS&AD Insurance': '8725.T',
  'Sompo Holdings': '8630.T',
  'Aozora Bank': '8304.T',
  'Chiba Bank': '8331.T',
  'Shizuoka Financial': '5831.T',
  'Fukuoka Financial': '8354.T',
  'Seven Bank': '8410.T',

  // European Luxury
  'LVMH': 'MC.PA',
  'Hermès': 'RMS.PA',
  'Richemont': 'CFR.SW',
  'Ferrari': 'RACE.MI',
  'Kering': 'KER.PA',
  'Moncler': 'MONC.MI',
  'Brunello Cucinelli': 'BC.MI',
  'Prada': '1913.HK',
  'Burberry': 'BRBY.L',
  'Swatch Group': 'UHR.SW',
  'Pandora': 'PNDORA.CO',
  'Hugo Boss': 'BOSS.DE',
  'Salvatore Ferragamo': 'SFER.MI',
  'Ermenegildo Zegna': 'ZGN',
  'Watches of Switzerland': 'WOSG.L',
  'Chow Tai Fook': '1929.HK',
  'EssilorLuxottica': 'EL.PA',
  'Christian Dior': 'CDI.PA',

  // India Infrastructure
  'Larsen & Toubro': 'LT.NS',
  'Adani Ports': 'ADANIPORTS.NS',
  'UltraTech Cement': 'ULTRACEMCO.NS',
  'Siemens India': 'SIEMENS.NS',
  'ABB India': 'ABB.NS',
  'Adani Enterprises': 'ADANIENT.NS',
  'Shree Cement': 'SHREECEM.NS',
  'Ambuja Cements': 'AMBUJACEM.NS',
  'Thermax': 'THERMAX.NS',
  'KNR Constructions': 'KNRCON.NS',
  'NCC Ltd': 'NCC.NS',
  'IRB Infrastructure': 'IRB.NS',
  'Dilip Buildcon': 'DBL.NS',
  'NBCC India': 'NBCC.NS',
  'Cummins India': 'CUMMINSIND.NS',
  'Bharat Electronics': 'BEL.NS',
  'Engineers India': 'ENGINERSIN.NS',
  'GMR Airports': 'GMRINFRA.NS',
  'PNC Infratech': 'PNCINFRA.NS',

  // Asia Semiconductors
  'TSMC': '2330.TW',
  'Samsung Electronics': '005930.KS',
  'SK Hynix': '000660.KS',
  'Tokyo Electron': '8035.T',
  'ASM Pacific': '0522.HK',
  'MediaTek': '2454.TW',
  'Renesas Electronics': '6723.T',
  'Advantest': '6857.T',
  'Screen Holdings': '7735.T',
  'Disco Corp': '6146.T',
  'Lasertec': '6920.T',
  'United Microelectronics': '2303.TW',
  'Nanya Technology': '2408.TW',
  'Rohm Co': '6963.T',
  'Murata Manufacturing': '6981.T',
  'TDK Corp': '6762.T',
  'Sumco Corp': '3436.T',
  'Win Semiconductors': '3105.TW',
  'Realtek Semiconductor': '2379.TW',

  // LatAm Commodities
  'Vale': 'VALE3.SA',
  'Grupo México': 'GMEXICOB.MX',
  'Southern Copper': 'SCCO',
  'SQM': 'SQM',
  'Petrobras': 'PETR4.SA',
  'Gerdau': 'GGBR4.SA',
  'Ternium': 'TX',
  'Cemex': 'CEMEXCPO.MX',
  'Suzano': 'SUZB3.SA',
  'Klabin': 'KLBN11.SA',
  'Braskem': 'BRKM5.SA',
  'Usiminas': 'USIM5.SA',
  'Ecopetrol': 'EC',
  'YPF': 'YPF',

  // European Green Energy
  'Iberdrola': 'IBE.MC',
  'Ørsted': 'ORSTED.CO',
  'Vestas': 'VWS.CO',
  'Siemens Energy': 'ENR.DE',
  'EDP Renováveis': 'EDPR.LS',
  'Enel': 'ENEL.MI',
  'RWE': 'RWE.DE',
  'SSE': 'SSE.L',
  'Nordex': 'NDX1.DE',
  'Solaria Energía': 'SLR.MC',
  'Acciona Energía': 'ANE.MC',
  'Verbund': 'VER.VI',
  'Encavis': 'CAP.DE',
  'Voltalia': 'VLTSA.PA',
  'Neoen': 'NEOEN.PA',

  // China Consumer
  'Alibaba': '9988.HK',
  'JD.com': '9618.HK',
  'PDD Holdings': 'PDD',
  'Meituan': '3690.HK',
  'Li Auto': '2015.HK',
  'BYD': '1211.HK',
  'Nio': 'NIO',
  'XPeng': '9868.HK',
  'Trip.com': '9961.HK',
  'Vipshop': 'VIPS',
  'Anta Sports': '2020.HK',
  'Li Ning': '2331.HK',
  'Haidilao': '6862.HK',
  'China Tourism Group Duty Free': '1880.HK',
  'Yum China': '9987.HK',
  'Pop Mart': '9992.HK',
  'Geely Auto': '0175.HK',

  // India IT Services
  'TCS': 'TCS.NS',
  'Infosys': 'INFY.NS',
  'Wipro': 'WIPRO.NS',
  'HCL Tech': 'HCLTECH.NS',
  'Tech Mahindra': 'TECHM.NS',
  'LTIMindtree': 'LTIM.NS',
  'Mphasis': 'MPHASIS.NS',
  'Persistent Systems': 'PERSISTENT.NS',
  'Coforge': 'COFORGE.NS',
  'L&T Technology Services': 'LTTS.NS',
  'Cyient': 'CYIENT.NS',
  'Zensar Technologies': 'ZENSARTECH.NS',
  'Birlasoft': 'BSOFT.NS',
  'KPIT Technologies': 'KPITTECH.NS',
  'Tata Elxsi': 'TATAELXSI.NS',
  'Firstsource Solutions': 'FSL.NS',
  'eClerx Services': 'ECLERX.NS',
  'Mastek': 'MASTEK.NS',
  'Happiest Minds': 'HAPPSTMNDS.NS',

  // European Banks
  'BNP Paribas': 'BNP.PA',
  'Deutsche Bank': 'DBK.DE',
  'UBS': 'UBSG.SW',
  'Santander': 'SAN.MC',
  'UniCredit': 'UCG.MI',
  'ING Group': 'INGA.AS',
  'Intesa Sanpaolo': 'ISP.MI',
  'Société Générale': 'GLE.PA',
  'Credit Agricole': 'ACA.PA',
  'BBVA': 'BBVA.MC',
  'Commerzbank': 'CBK.DE',
  'ABN AMRO': 'ABN.AS',
  'Nordea': 'NDA-FI.HE',
  'Danske Bank': 'DANSKE.CO',
  'CaixaBank': 'CABK.MC',
  'KBC Group': 'KBC.BR',
  'Bankinter': 'BKT.MC',
  'Erste Group': 'EBS.VI',
  'DNB Bank': 'DNB.OL',
  'Swedbank': 'SWED-A.ST',

  // Korea EV & Batteries
  'LG Energy Solution': '373220.KS',
  'Samsung SDI': '006400.KS',
  'SK Innovation': '096770.KS',
  'Hyundai Motor': '005380.KS',
  'POSCO Future M': '003670.KS',
  'Kia Corp': '000270.KS',
  'LG Chem': '051910.KS',
  'EcoPro BM': '247540.KS',
  'EcoPro': '086520.KS',
  'L&F Co': '066970.KS',
  'POSCO Holdings': '005490.KS',
  'Samsung Electro-Mechanics': '009150.KS',
  'Hanon Systems': '018880.KS',
  'Hyundai Mobis': '012330.KS',
  'SK IE Technology': '361610.KS',
  'Doosan Fuel Cell': '336260.KS',

  // Japan Automation
  'Fanuc': '6954.T',
  'Keyence': '6861.T',
  'SMC Corp': '6273.T',
  'Yaskawa': '6506.T',
  'Nidec': '6594.T',
  'Omron': '6645.T',
  'Mitsubishi Electric': '6503.T',
  'Komatsu': '6301.T',
  'Kubota': '6326.T',
  'Daikin Industries': '6367.T',
  'THK': '6481.T',
  'Nabtesco': '6268.T',
  'Daifuku': '6383.T',
  'Hamamatsu Photonics': '6965.T',
  'Shimadzu': '7701.T',
  'Amada Holdings': '6113.T',
  'DMG Mori': '6141.T',

  // ASEAN Growth
  'DBS Group': 'D05.SI',
  'Bank Central Asia': 'BBCA.JK',
  'Sea Limited': 'SE',
  'Grab Holdings': 'GRAB',
  'Bangkok Bank': 'BBL.BK',
  'OCBC': 'O39.SI',
  'UOB': 'U11.SI',
  'Bank Rakyat Indonesia': 'BBRI.JK',
  'Bank Mandiri': 'BMRI.JK',
  'Telkom Indonesia': 'TLKM.JK',
  'Kasikornbank': 'KBANK.BK',
  'Public Bank Malaysia': '1295.KL',
  'CIMB Group': '1023.KL',
  'Maybank': '1155.KL',
  'Singapore Telecom': 'Z74.SI',
  'SM Investments': 'SM.PS',
  'BDO Unibank': 'BDO.PS',

  // European Pharma
  'Novo Nordisk': 'NOVO-B.CO',
  'AstraZeneca': 'AZN.L',
  'Roche': 'ROG.SW',
  'Novartis': 'NOVN.SW',
  'Sanofi': 'SAN.PA',
  'GSK': 'GSK.L',
  'Bayer': 'BAYN.DE',
  'UCB': 'UCB.BR',
  'Genmab': 'GMAB.CO',
  'Lonza': 'LONN.SW',
  'Straumann': 'STMN.SW',
  'Sartorius': 'SRT.DE',
  'Ipsen': 'IPN.PA',
  'Hikma Pharmaceuticals': 'HIK.L',
  'Recordati': 'REC.MI',
  'Zealand Pharma': 'ZEAL.CO',
  'Argenx': 'ARGX.BR',

  // Australia Resources
  'BHP': 'BHP.AX',
  'Rio Tinto': 'RIO.AX',
  'Fortescue': 'FMG.AX',
  'Pilbara Minerals': 'PLS.AX',
  'Newmont': 'NEM.AX',
  'South32': 'S32.AX',
  'Northern Star Resources': 'NST.AX',
  'Evolution Mining': 'EVN.AX',
  'Mineral Resources': 'MIN.AX',
  'Lynas Rare Earths': 'LYC.AX',
  'IGO Limited': 'IGO.AX',
  'Sandfire Resources': 'SFR.AX',
  'Iluka Resources': 'ILU.AX',
  'Whitehaven Coal': 'WHC.AX',
  'Woodside Energy': 'WDS.AX',
  'Santos': 'STO.AX',
  'Champion Iron': 'CIA.AX',
  'Regis Resources': 'RRL.AX',

  // Gulf Diversification
  'Saudi Aramco': '2222.SR',
  'Emaar Properties': 'EMAAR.DU',
  'Saudi Telecom': '7010.SR',
  'QNB Group': 'QNBK.QA',
  'First Abu Dhabi Bank': 'FAB.AD',
  'Al Rajhi Bank': '1120.SR',
  'Emirates NBD': 'ENBD.DU',
  'Saudi National Bank': '1180.SR',
  'Aldar Properties': 'ALDAR.AD',
  'Etisalat': 'ETISALAT.AD',
  'SABIC': '2010.SR',

  // India Financials
  'HDFC Bank': 'HDFCBANK.NS',
  'ICICI Bank': 'ICICIBANK.NS',
  'Bajaj Finance': 'BAJFINANCE.NS',
  'SBI': 'SBIN.NS',
  'Kotak Mahindra': 'KOTAKBANK.NS',
  'Axis Bank': 'AXISBANK.NS',
  'IndusInd Bank': 'INDUSINDBK.NS',
  'Bajaj Finserv': 'BAJAJFINSV.NS',
  'Bandhan Bank': 'BANDHANBNK.NS',
  'IDFC First Bank': 'IDFCFIRSTB.NS',
  'Shriram Finance': 'SHRIRAMFIN.NS',
  'Muthoot Finance': 'MUTHOOTFIN.NS',
  'Cholamandalam Investment': 'CHOLAFIN.NS',
  'AU Small Finance Bank': 'AUBANK.NS',
  'Federal Bank': 'FEDERALBNK.NS',
  'RBL Bank': 'RBLBANK.NS',
  'Punjab National Bank': 'PNB.NS',
  'Bank of Baroda': 'BANKBARODA.NS',
  'HDFC Life Insurance': 'HDFCLIFE.NS',

  // China AI & Tech
  'Tencent': '0700.HK',
  'Baidu': '9888.HK',
  'SenseTime': '0020.HK',
  'Xiaomi': '1810.HK',
  'NetEase': '9999.HK',
  'Kuaishou': '1024.HK',
  'Bilibili': '9626.HK',
  'ZTE Corp': '0763.HK',
  'Kingsoft': '3888.HK',
  'Weibo': '9898.HK',
  'Hikvision': '002415.SZ',
  'Lenovo': '0992.HK',
  'SMIC': '0981.HK',

  // Canada Energy
  'Canadian Natural Resources': 'CNQ.TO',
  'Suncor': 'SU.TO',
  'Enbridge': 'ENB.TO',
  'TC Energy': 'TRP.TO',
  'Cenovus': 'CVE.TO',
  'Imperial Oil': 'IMO.TO',
  'Pembina Pipeline': 'PPL.TO',
  'Keyera Corp': 'KEY.TO',
  'ARC Resources': 'ARX.TO',
  'Tourmaline Oil': 'TOU.TO',
  'MEG Energy': 'MEG.TO',
  'Vermilion Energy': 'VET.TO',
  'Whitecap Resources': 'WCP.TO',
  'Crescent Point Energy': 'CPG.TO',
  'Gibson Energy': 'GEI.TO',
  'Baytex Energy': 'BTE.TO',
  'Freehold Royalties': 'FRU.TO',
  'Birchcliff Energy': 'BIR.TO',

  // UK Consumer Staples
  'Unilever': 'ULVR.L',
  'Diageo': 'DGE.L',
  'Reckitt': 'RKT.L',
  'Associated British Foods': 'ABF.L',
  'Tesco': 'TSCO.L',
  'British American Tobacco': 'BATS.L',
  'Imperial Brands': 'IMB.L',
  'Haleon': 'HLN.L',
  'Marks & Spencer': 'MKS.L',
  'Kerry Group': 'KRZ.IR',
  'Ocado': 'OCDO.L',
  'Greggs': 'GRG.L',
  'Premier Foods': 'PFD.L',
  'Cranswick': 'CWK.L',
  'Fever-Tree': 'FEVR.L',
}
